### ISSUE TITLE
login problem 

### ISSUE THREAD

**Issue by Kira-0007** [itszechs/DriveStream#66] opened 2022-11-25 14:37 UTC
![IMG_20221125_200100](https://user-images.githubusercontent.com/105588608/204006439-1200a23c-0305-4dd9-9345-cc97423e474a.jpg)

Bro please please please help.. this is one of the best app i found on internet and now this login problem happend... Please i request you please fix this issue..
May god return you your ex ☺️

**Comment by itszechs** [comment] 2022-11-25 17:06
Duplicate of #63

**Closed by itszechs** 2022-11-25 17:06 UTC
Labels: duplicate

**Comment by Kira-0007** [comment] 2022-11-26 00:28
Is this getting a new update soon ?
